name: flutter_tags
description: Create beautiful tags quickly and easily.
version: 0.4.0
author: Antonino Di Natale <gyorgio88@gmail.com>
homepage: https://github.com/Dn-a/flutter_tags

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
