name: flutter_tags
description: An implementation of Selectable or Input tags.
version: 0.1.0
author: Antonino Di Natale <gyorgio88@gmail.com>
homepage: https://github.com/Dn-a/flutter_tags

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
